import { TourPackage } from "@/types/package";

export const allPackages: TourPackage[] = [
  {
    id: 1,
    title: "Hunza Valley Adventure",
    destination: "Hunza, Pakistan",
    category: "Domestic Tour",
    image: "/assets/images/packages/hunza.jpg",
    duration: "7 Days / 6 Nights",
    departureDate: "15 Aug 2026",
    price: 65000,
    originalPrice: 75000,
    availableSeats: 12,
    rating: 4.8,
    totalReviews: 124,
    discount: 13,
  },
  {
    id: 2,
    title: "Skardu Premium Tour",
    destination: "Skardu, Pakistan",
    category: "Domestic Tour",
    image: "/assets/images/packages/skardu.jpg",
    duration: "6 Days / 5 Nights",
    departureDate: "20 Sept 2026",
    price: 75000,
    originalPrice: 85000,
    availableSeats: 9,
    rating: 4.7,
    totalReviews: 156,
    discount: 12,
  },
  {
    id: 3,
    title: "Fairy Meadows Camping",
    destination: "Fairy Meadows, Pakistan",
    category: "Adventure Tour",
    image: "/assets/images/packages/fairy-meadows.jpg",
    duration: "5 Days / 4 Nights",
    departureDate: "10 Sept 2026",
    price: 58000,
    originalPrice: 65000,
    availableSeats: 15,
    rating: 4.9,
    totalReviews: 93,
    discount: 11,
  },
  {
    id: 4,
    title: "Swat Family Escape",
    destination: "Swat, Pakistan",
    category: "Family Tour",
    image: "/assets/images/packages/swat.jpg",
    duration: "4 Days / 3 Nights",
    departureDate: "28 Aug 2026",
    price: 42000,
    originalPrice: 48000,
    availableSeats: 18,
    rating: 4.6,
    totalReviews: 78,
    discount: 13,
  },
  {
    id: 5,
    title: "Naran Kaghan Explorer",
    destination: "Naran Kaghan, Pakistan",
    category: "Adventure Tour",
    image: "/assets/images/packages/naran.jpg",
    duration: "5 Days / 4 Nights",
    departureDate: "18 Sept 2026",
    price: 49000,
    originalPrice: 56000,
    availableSeats: 14,
    rating: 4.7,
    totalReviews: 112,
    discount: 12,
  },
  {
    id: 6,
    title: "Neelum Valley Retreat",
    destination: "Neelum Valley, Pakistan",
    category: "Family Tour",
    image: "/assets/images/packages/neelum.jpg",
    duration: "6 Days / 5 Nights",
    departureDate: "25 Sept 2026",
    price: 62000,
    originalPrice: 70000,
    availableSeats: 10,
    rating: 4.8,
    totalReviews: 101,
    discount: 11,
  },
  {
    id: 7,
    title: "Murree Weekend Getaway",
    destination: "Murree, Pakistan",
    category: "Weekend Tour",
    image: "/assets/images/packages/murree.jpg",
    duration: "3 Days / 2 Nights",
    departureDate: "12 Aug 2026",
    price: 25000,
    originalPrice: 29000,
    availableSeats: 22,
    rating: 4.5,
    totalReviews: 210,
    discount: 14,
  },
  {
    id: 8,
    title: "Azad Kashmir Discovery",
    destination: "Muzaffarabad, Pakistan",
    category: "Domestic Tour",
    image: "/assets/images/packages/kashmir.jpg",
    duration: "5 Days / 4 Nights",
    departureDate: "8 Sept 2026",
    price: 54000,
    originalPrice: 61000,
    availableSeats: 11,
    rating: 4.8,
    totalReviews: 145,
    discount: 11,
  },
  {
    id: 9,
    title: "Turkey Explorer",
    destination: "Istanbul & Cappadocia",
    category: "International Tour",
    image: "/assets/images/packages/turkey.jpg",
    duration: "8 Days / 7 Nights",
    departureDate: "5 Sept 2026",
    price: 285000,
    originalPrice: 315000,
    availableSeats: 6,
    rating: 4.9,
    totalReviews: 98,
    discount: 10,
  },
  {
    id: 10,
    title: "Dubai Luxury Escape",
    destination: "Dubai, UAE",
    category: "International Tour",
    image: "/assets/images/packages/dubai.jpg",
    duration: "5 Days / 4 Nights",
    departureDate: "30 Sept 2026",
    price: 175000,
    originalPrice: 195000,
    availableSeats: 8,
    rating: 4.8,
    totalReviews: 185,
    discount: 10,
  },
  {
    id: 11,
    title: "Azerbaijan Highlights",
    destination: "Baku, Azerbaijan",
    category: "International Tour",
    image: "/assets/images/packages/azerbaijan.jpg",
    duration: "6 Days / 5 Nights",
    departureDate: "22 Sept 2026",
    price: 165000,
    originalPrice: 182000,
    availableSeats: 13,
    rating: 4.7,
    totalReviews: 86,
    discount: 9,
  },
  {
    id: 12,
    title: "Malaysia Experience",
    destination: "Kuala Lumpur, Malaysia",
    category: "International Tour",
    image: "/assets/images/packages/malaysia.jpg",
    duration: "7 Days / 6 Nights",
    departureDate: "3 Oct 2026",
    price: 235000,
    originalPrice: 255000,
    availableSeats: 7,
    rating: 4.9,
    totalReviews: 134,
    discount: 8,
  },
  {
    id: 13,
    title: "Thailand Island Adventure",
    destination: "Phuket, Thailand",
    category: "Honeymoon Tour",
    image: "/assets/images/packages/thailand.jpg",
    duration: "7 Days / 6 Nights",
    departureDate: "12 Oct 2026",
    price: 225000,
    originalPrice: 245000,
    availableSeats: 9,
    rating: 4.8,
    totalReviews: 141,
    discount: 8,
  },
  {
    id: 14,
    title: "Bali Honeymoon Special",
    destination: "Bali, Indonesia",
    category: "Honeymoon Tour",
    image: "/assets/images/packages/bali.jpg",
    duration: "6 Days / 5 Nights",
    departureDate: "18 Oct 2026",
    price: 245000,
    originalPrice: 270000,
    availableSeats: 5,
    rating: 5.0,
    totalReviews: 174,
    discount: 9,
  },
  {
    id: 15,
    title: "Umrah Spiritual Journey",
    destination: "Makkah & Madinah",
    category: "Religious Tour",
    image: "/assets/images/packages/umrah.jpg",
    duration: "10 Days / 9 Nights",
    departureDate: "25 Oct 2026",
    price: 310000,
    originalPrice: 335000,
    availableSeats: 20,
    rating: 4.9,
    totalReviews: 267,
    discount: 7,
  },
];