export const destinations = [
  {
    id: 1,
    name: "Hunza Valley",
    country: "Pakistan",
    region: "Northern Pakistan",
    tours: 15,
    image: "/assets/images/destinations/hunza.jpg",
  },
  {
    id: 2,
    name: "Skardu",
    country: "Pakistan",
    region: "Northern Pakistan",
    tours: 12,
    image: "/assets/images/destinations/skardu.jpg",
  },
  {
    id: 3,
    name: "Swat",
    country: "Pakistan",
    region: "Khyber Pakhtunkhwa",
    tours: 10,
    image: "/assets/images/destinations/swat.jpg",
  },
  {
    id: 4,
    name: "Turkey",
    country: "International",
    region: "Europe / Asia",
    tours: 8,
    image: "/assets/images/destinations/turkey.jpg",
  },
  {
    id: 5,
    name: "Dubai",
    country: "International",
    region: "Middle East",
    tours: 9,
    image: "/assets/images/destinations/dubai.jpg",
  },
  {
    id: 6,
    name: "Thailand",
    country: "International",
    region: "Southeast Asia",
    tours: 7,
    image: "/assets/images/destinations/thailand.jpg",
  },
];